/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Producto } from "./Producto";
import { ProductoCountArgs } from "./ProductoCountArgs";
import { ProductoFindManyArgs } from "./ProductoFindManyArgs";
import { ProductoFindUniqueArgs } from "./ProductoFindUniqueArgs";
import { CreateProductoArgs } from "./CreateProductoArgs";
import { UpdateProductoArgs } from "./UpdateProductoArgs";
import { DeleteProductoArgs } from "./DeleteProductoArgs";
import { ProveedorFindManyArgs } from "../../proveedor/base/ProveedorFindManyArgs";
import { Proveedor } from "../../proveedor/base/Proveedor";
import { ProductoService } from "../producto.service";
@graphql.Resolver(() => Producto)
export class ProductoResolverBase {
  constructor(protected readonly service: ProductoService) {}

  async _productosMeta(
    @graphql.Args() args: ProductoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Producto])
  async productos(
    @graphql.Args() args: ProductoFindManyArgs
  ): Promise<Producto[]> {
    return this.service.productos(args);
  }

  @graphql.Query(() => Producto, { nullable: true })
  async producto(
    @graphql.Args() args: ProductoFindUniqueArgs
  ): Promise<Producto | null> {
    const result = await this.service.producto(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Producto)
  async createProducto(
    @graphql.Args() args: CreateProductoArgs
  ): Promise<Producto> {
    return await this.service.createProducto({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Producto)
  async updateProducto(
    @graphql.Args() args: UpdateProductoArgs
  ): Promise<Producto | null> {
    try {
      return await this.service.updateProducto({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Producto)
  async deleteProducto(
    @graphql.Args() args: DeleteProductoArgs
  ): Promise<Producto | null> {
    try {
      return await this.service.deleteProducto(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Proveedor], { name: "proveedors" })
  async findProveedors(
    @graphql.Parent() parent: Producto,
    @graphql.Args() args: ProveedorFindManyArgs
  ): Promise<Proveedor[]> {
    const results = await this.service.findProveedors(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
